### ISSUE TITLE
Email verification not working with Docker Image, do not have access to self hosted site

### ISSUE THREAD

**Issue by fmcpherson** [monicahq/monica#1453]
**Describe the bug**
NOTE: I presently have a outage of my local installation!

After performing a docker-compose pull for my local installation, I am directed to a login page. Upon entering my credentials the page re-displays with a message saying that I must verify my email and to look for a message in my inbox that never arrives. 

I also selected the option to change my email address, which then says to check my mailbox, but again I never receive email. 

I also changed my password, and while that appears to have worked it does not resolve the email validation. 

I have checked my Spam folder and have not received any emails.

I effectively cannot access my information in my local installation, which is a problem. Is there an option that I can add to .ENV? 

I've enabled debug but I am not seeing any error messages. 

**Screenshots**
If you can, add screenshots to help explain your problem. An image is always helpful.

**Which version are you using:**
Self hosted, I believe I pulled the latest image from docker hub that I believe has version 2.2.1 per the tag information on docker hub. Can we confirm that the docker image does in fact have version 2.2.1 because the change log suggests what I am seeing is a known error in 2.2.0 and what I am seeing is acting as if I am still using that version.  

**Additional context**
I assume this process is using the same SMTP server as what is used for sending reminders. I did

**Comment by fmcpherson** [comment]
I attempted to create a new user to see what happens and get dumped to the following error page.
[monicaErrorWhenCreatingNewUser.pdf](https://github.com/monicahq/monica/files/2068960/monicaErrorWhenCreatingNewUser.pdf)

**Comment by fmcpherson** [comment]
If I get in to the image by doing docker-compose run monicahq shell, is there any easy way to confirm that the files inside the container are the most current? I did a ls -l to look at the dates of the files and see May 31.

**Comment by privong** [comment]
This is more of a workaround than a fix, but I went into my database and set the `confirmed` entry for my user to `1`. Something like

```
USE monica;
UPDATE users SET confirmed=1 WHERE email="myemail";
```

**Comment by fmcpherson** [comment]
Are you using the docker version of Monica and if so how are you access mysql? 

I note there is a setting .env that I think is basically supposed to do the above that is not working, or perhaps that option is only for new users but as you can see, I can't even add a new user to my instance so something is definitely messed up.

**Comment by privong** [comment]
I am using a standalone install (not inside Docker), sorry. I'm afraid I'm not familiar with getting into the SQL CLI via docker.

> I note there is a setting .env that I think is basically supposed to do the above that is not working, or perhaps that option is only for new users.

Do you mean the `APP_DISABLE_SIGNUP=` option? I don't believe that has anything to do with requesting confirmation and only deals with new user creation.

**Comment by fmcpherson** [comment]
Not that setting, a new one was added for this feature. See here: 

https://github.com/monicahq/monica/commit/a79c19dd6c79fd30f833d8932bdedeebb4716370 

I can't translate the code to determine what is going on, but I am never receiving the notification emails so it is behaving as if it were never sent. One thing I do wonder about since it might be using the reminder code, is if the confirmations are not being immediately sent. The only thing I have been able to successfully do is change the email address for my user.

**Comment by privong** [comment]
Ah okay, I hadn't updated my .env to the latest version. I'm also not familiar enough with the code to say what's going on. Sorry.

**Comment by fmcpherson** [comment]
Not that setting, a new one was added for this feature. See here: 

https://github.com/monicahq/monica/commit/a79c19dd6c79fd30f833d8932bdedeebb4716370 

I can't translate the code to determine what is going on, but I am never receiving the notification emails so it is behaving as if it were never sent. One thing I do wonder about since it might be using the reminder code, is if the confirmations are not being immediately sent. The only thing I have been able to successfully do is change the email address for my user.

**Comment by JCBird1012** [comment]
You're correct — the verification emails are never sending, it happens for me as well.

As for accessing the ```mysql``` shell, you can do something like ```docker exec -it``` **[INSERT NAME OF DATABASE CONTAINER HERE]** ```bash```.

Then at the shell, run the command ```mysql -u``` **[MYSQL USER HERE]** (which by default is **homestead**), and the password defined in your ```.env``` file. Then run @privong's command.

**Comment by fmcpherson** [comment]
For the moment I have reverted back to 2.1.1 so that I can access my instance. I am hoping that the developers fix this bug before I have to try making the manual change.

**Comment by fmcpherson** [comment]
I am concerned that this thread has not yet been flagged as a bug. It appears to me that functionality basic to 2.2.0 does not work, and upgrading to it renders my implement unusable. I don't understand how anyone can consider this acceptable.

**Comment by JCBird1012** [comment]
This can be closed. It was solved in #1463.

**Comment by dosch** [comment]
I also locked myself out of my Monica installation. But I used Yunohost to install it. 
If you say this is fixed, will it mean that next time I update Monica, I can access the app again? Or do I need to do something else to regain access?

**Comment by JCBird1012** [comment]
@dosch Yes, that should work. Updating Monica to at least >= 2.3.0 should allow the account reset logic to work properly again.

**Comment by dosch** [comment]
sadly it wasn't so, I went from 2.1.1 to 2.3 when this happened.
Anyway, I reinstalled by now.

**Comment by fmcpherson** [comment]
Just tested the upgraded to version 2.3 and I can report the issue still exists! I cannot get past the email verification and consequently am locked out of my install.

**Comment by asbiin** [comment]
Hi.
Sorry all for the delay ...
The email verification needs the configuration of the 'Mail credentials' part.
But, you can set `APP_SIGNUP_DOUBLE_OPTIN=false` to deactivate email verification completely.
