### ISSUE TITLE
Cannot re-add photos to some contacts after Monica migration 

### ISSUE THREAD

**Issue by mgrhm** [monicahq/monica#5257]
Since migrating to a fresh install of Monica, I can't re-add photos some contacts that previously had photos.  When trying to, I get this error dialogue:

<img width="408" alt="Screenshot 2021-06-07 at 08 23 08" src="https://user-images.githubusercontent.com/21129642/120976906-aeea8d00-c76a-11eb-9806-bfb8cf4b99c2.png">

Strangely, this doesn't happen with all contacts who previously had photos -- only some of them.  It happens if I use new photos or try to use the ones I previously used which I'd grabbed from Monica before reinstalling.

**Comment by asbiin** [comment]
What are the data sent to the request?

**Comment by mgrhm** [comment]
The data is just a photo in JPEG format. It happens if I use the same photo as before, or if I use a different one.

**Comment by nhymxu** [comment]
I checked that file path is `public/storage/photos`
But new version using url `http://monica.instance/store/photos`

So is it problem?

**Comment by mgrhm** [comment]
It appears to have been fixed by resetting Monica to v3.0.1 and then running

    php artisan monica:update --force

Thanks everyone for your help!

**Comment by mgrhm** [comment]
There’s something more at play here.  Some of the contacts can be changed, some can't.  I'm running 3.1.1 and still having this issue inconsistently.  Running the `monica:update` command doesn't fix it.

**Comment by Brice187** [comment]
still an issue in 3.5.0

**Comment by sebklaus** [comment]
It's still an issue in 3.6.1. Avatar uploads work perfectly fine when done from a Desktop, but using in-built camera on a tablet (for example) results in this error. Picking a photo from the Library works, sometimes. No Laravel logs are created, docker logs show 302 as stated above.

**Comment by mgrhm** [comment]
I finally upgraded to 3.7.0, and this issue still exists.
